### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AlexHamn** [AlexHamn/portfolio#5]

**Comment by rotimiazeez** [comment]
Hi @AlexHamn 🎉 
What a great code you have here 👍🏽 but I like to suggest a few things to help improve your code 🤷🏽‍♂️.
I think it better to have a reset code to make your code DRY (don't repeat yourself) 👍🏽 .
I will also suggest that you try to copy the Figma template as much as you can (e.g., font, colours, images, tests, margins) 💪🏽
